### ISSUE TITLE
error

### ISSUE THREAD

**Issue by ghost** [EvanStanford/cams#3]
Hi,
when I follow your instruction and I cd into the main file to execute go install I get the following error:
.\main.go:18: undefined: strconv in strconv.ParseFloat
I am new to go language and would highly appreciate your comment to this topic...

**Comment by EvanStanford** [comment]
Looks like I somehow forgot to import "strconv". I will fix this tonight. Until then, try adding it to the imports list:

``` diff
import (
	"os"
	"path/filepath"
	"github.com/EvanStanford/cams/profiler"
+	"strconv"
)
```
